// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "From shorten url redirect to original shotened url",
                "tags": [
                    "Shortener"
                ],
                "summary": "Redirect to original url",
                "responses": {
                    "301": {
                        "description": "Moved Permanently"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "410": {
                        "description": "Gone"
                    }
                }
            }
        },
        "/health/": {
            "get": {
                "description": "Chech API Health",
                "tags": [
                    "Health"
                ],
                "summary": "Check API Health",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "410": {
                        "description": "Gone"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:7878",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Shortic API documentation",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
