// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "From shorten url redirect to original shotened url",
                "tags": [
                    "Shortener"
                ],
                "summary": "Redirect to original url",
                "responses": {
                    "301": {
                        "description": "Moved Permanently"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/data/shortener": {
            "post": {
                "tags": [
                    "Shortener"
                ],
                "parameters": [
                    {
                        "description": "Url",
                        "name": "Url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/shortener.postUrlBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shortener.responsePostBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/health/": {
            "get": {
                "description": "Chech API Health",
                "tags": [
                    "Health"
                ],
                "summary": "Check API Health",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "shortener.postUrlBody": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "shortener.responsePostBody": {
            "type": "object",
            "properties": {
                "shortenUrl": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:7878",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Shortic API documentation",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
