basePath: /
host: localhost:7878
info:
  contact: {}
  title: Shortic API documentation
  version: 0.0.1
paths:
  /:
    get:
      description: From shorten url redirect to original shotened url
      responses:
        "301":
          description: Moved Permanently
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "410":
          description: Gone
      summary: Redirect to original url
      tags:
      - Shortener
  /health/:
    get:
      description: Chech API Health
      responses:
        "200":
          description: OK
        "410":
          description: Gone
      summary: Check API Health
      tags:
      - Health
swagger: "2.0"
